language: node_js

node_js:
  - "12"

sudo: required

env:
  - DOCKER_COMPOSE_VERSION=1.24.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  - cp .env.example .env
  - docker-compose up -d db
  - npm install -g npm@^6 wait-on

services:
  - docker

install: npm ci

before_script:
  - npm run e2e:migrate

script:
- npm run test:unit
- NODE_TEST=1 npm run build
- NODE_TEST=1 npm run start &
- PID1=$!
- wait-on http://localhost:3000/about && npm run test:integration
- npm run test:e2e
- kill $PID1
