version: "2"

services:
  db:
    image: bitnami/postgresql:10
    volumes:
      - ./.pgdata:/bitnami
    ports:
      - "5432:5432"
    env_file: .env

  app:
    build: .
    env_file: .env
    environment:
      POSTGRESQL_HOST: db
    command: "./entrypoint.sh"
    links:
      - db:db
    ports:
      - "3000:3000"
